services:

  postgres:
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "guest"
      POSTGRES_USER: "guest"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      default:

networks:
  default:

volumes:
  postgres:
